# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_dtou <- function(RString, rc) {
    .Call('_dtou_c_dtou', PACKAGE = 'dtou', RString, rc)
}

c_dtouDepthLimit <- function(RString, rc, depth) {
    .Call('_dtou_c_dtouDepthLimit', PACKAGE = 'dtou', RString, rc, depth)
}

c_dtouS2 <- function(RString, rc) {
    .Call('_dtou_c_dtouS2', PACKAGE = 'dtou', RString, rc)
}

c_dtouS2B <- function(RString, rc) {
    .Call('_dtou_c_dtouS2B', PACKAGE = 'dtou', RString, rc)
}

c_dtouS2DepthLimit <- function(RString, rc, depth) {
    .Call('_dtou_c_dtouS2DepthLimit', PACKAGE = 'dtou', RString, rc, depth)
}

c_vignetteExample <- function(RString, rc) {
    .Call('_dtou_c_vignetteExample', PACKAGE = 'dtou', RString, rc)
}

