# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_dtou <- function(RString) {
    .Call('_dtou_c_dtou', PACKAGE = 'dtou', RString)
}

c_limiteddtou <- function(RString, depth) {
    .Call('_dtou_c_limiteddtou', PACKAGE = 'dtou', RString, depth)
}

c_dtouC <- function(RString) {
    .Call('_dtou_c_dtouC', PACKAGE = 'dtou', RString)
}

c_limiteddtouC <- function(RString, depth) {
    .Call('_dtou_c_limiteddtouC', PACKAGE = 'dtou', RString, depth)
}

